name: Feature Request
  description: Suggest a new feature or improvement for Channel Tools
  title: "[Feature] "
  labels: ["enhancement"]
  body:
    - type: markdown
      attributes:
        value: |
          Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand 
  your idea.

    - type: textarea
      id: problem
      attributes:
        label: Problem or Need
        description: What problem would this feature solve? What need does it address?
        placeholder: I'm frustrated when... / It would be helpful if... / Currently there's no way to...
      validations:
        required: true

    - type: textarea
      id: solution
      attributes:
        label: Proposed Solution
        description: Describe the feature you'd like to see
        placeholder: I would like... / The feature should... / It could work by...
      validations:
        required: true

    - type: dropdown
      id: category
      attributes:
        label: Feature Category
        description: Which area of Channel Tools would this feature relate to?
        options:
          - Dashboard & Analytics
          - YouTube Optimizer
          - Channel Review
          - Thumbnail Review
          - Description Templates
          - Settings & Configuration
          - User Interface
          - API Integration
          - Other
      validations:
        required: true

    - type: dropdown
      id: priority
      attributes:
        label: How important is this feature to you?
        options:
          - Critical - I can't use Channel Tools effectively without it
          - High - Would significantly improve my workflow
          - Medium - Would be nice to have
          - Low - Just a small improvement
      validations:
        required: true

    - type: textarea
      id: use-case
      attributes:
        label: Use Case
        description: Describe how you would use this feature in your workflow
        placeholder: When I'm... I would use this feature to... This would help me...

    - type: textarea
      id: alternatives
      attributes:
        label: Alternatives Considered
        description: Have you considered any workarounds or alternative solutions?
        placeholder: Currently I work around this by... / I've tried... / Other tools do this by...

    - type: textarea
      id: additional
      attributes:
        label: Additional Context
        description: Add any other context, mockups, or examples about the feature request
        placeholder: Links to examples, mockups, or any other helpful context...

